name: curvy_connection
description: Library to draw connection arrow for graphs, flow charts, mind maps, etc.
repository: https://github.com/tejainece/connection_arrow

version: 1.0.1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true